apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Bhavishya101/argo-demo-private.git
  password: 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 # password goes here, NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops.
  username: Bhavishya101

