apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app-composite
  namespace: argocd
spec:
  destination:
    namespace: composite-ns
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: 03-infra-manifests
    repoURL: "https://github.com/Bhavishya101/argo-crossplane-repo.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true
