apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: XGke.gke-demo-api.example.org
spec:
  group: gke-demo-api.example.org
  names:
    kind: XGke
    plural: Xgke
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                # oneOf:
                #   - pattern: '^EU$'
                #   - pattern: '^US$'
            required:
              - location
  claimNames:
    kind: Gke
    plural: gke